version: '1'

services:

  database:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: typescript-koa

  server:
    image: server:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery
